name: Ruby

on: [push]

jobs:
  test:
    name: CI-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
        client:
          - 'trilogy'
          - 'mysql2'

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: scenic_mysql_adapter_test
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        env:
          DATABASE_URL: ${{ matrix.client }}://root:root@127.0.0.1/scenic_mysql_adapter_test
        run: |
          bundle exec rake test
